name: run all tests

language: python
# python versions to use during the tests
python:
    - "3.7"
    - "3.4"
    - "3.9"
    - "3.2"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - pytest
branches:
  only:
   - main
