name: CodeCov

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install coverage
    - name: Generate Report 
      run: |
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2